### ISSUE TITLE
the demo page is down

### ISSUE THREAD

**Issue by renny-ren** [cprodhomme/arctic_admin#102]
:warning: ArcticAdmin is a simple gem, if you found a bug, you can easily fix it and make a pull-request. :pray: Thanks !

**Describe the bug**
The demo page is down: https://arctic-admin.herokuapp.com/

**To Reproduce**
Go to https://arctic-admin.herokuapp.com/ and you'll see the error.

**Expected behavior**
the page is shown correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/19547819/209104223-738c0cb5-5600-4c7b-a2a3-7bede12e1615.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Gemfile**
Place here your gemfile.lock of your project

**Additional context**

**Comment by cprodhomme** [comment]
Hello !

Since Heroku change theirs pricing, i can't make the demo for free.

Do you have any suggestion ?

**Comment by renny-ren** [comment]
> Hello !
> 
> Since Heroku change theirs pricing, i can't make the demo for free.
> 
> Do you have any suggestion ?

Maybe you can try [fly.io](https://fly.io/), it's cheaper than Heroku.

**Comment by cprodhomme** [comment]
I will deploy this app on [Scalingo](https://scalingo.com/) (it's an Heroku like with whom I used to work) but for now, i don't have time to do this :)

**Comment by cprodhomme** [comment]
Hello !

This is the new link of the demo : [https://arcticadmin.osc-fr1.scalingo.io](https://arcticadmin.osc-fr1.scalingo.io)
