### ISSUE TITLE
Variable $border-color cannot overwritten

### ISSUE THREAD

**Issue by galvadiz** [cprodhomme/arctic_admin#103]
Archive [arctic_admin](https://github.com/cprodhomme/arctic_admin)/[app](https://github.com/cprodhomme/arctic_admin/tree/master/app)/[assets](https://github.com/cprodhomme/arctic_admin/tree/master/app/assets)/[stylesheets](https://github.com/cprodhomme/arctic_admin/tree/master/app/assets/stylesheets)/[arctic_admin](https://github.com/cprodhomme/arctic_admin/tree/master/app/assets/stylesheets/arctic_admin)/[variables](https://github.com/cprodhomme/arctic_admin/tree/master/app/assets/stylesheets/arctic_admin/variables)/_colors.scss all variables have `!default` except `$border-color`. So, it is not possible customize this color in `active_admin.scss`.

Is it possible to fix this? Or is there a reason to do it like this?

**Comment by cprodhomme** [comment]
Hello @galvadiz 

It was a mistake ! Thanks for the feedback
