### ISSUE TITLE
The filter menu does not scroll on the mobile device

### ISSUE THREAD

**Issue by mario-amazing** [cprodhomme/arctic_admin#113]
On mobile devise I can't scroll till the search button.

**Expected behavior**
Scroll all of the filter menu

**Screenshots**
![IMG_AA479BBDACE0-1](https://github.com/cprodhomme/arctic_admin/assets/9537753/df2ed67e-bb0f-41c9-a229-6af6a7dd31dc)

 - iPhone xs
 - Browser Brave, Chrome
 - Version: latest

**Gemfile**
``` 
   arctic_admin (4.2.3)
   activeadmin (2.14.0)
```

**Comment by cprodhomme** [comment]
i know this bug since a long time but i don't know how to fix it

**Comment by mario-amazing** [comment]
@cprodhomme could you check it? https://github.com/cprodhomme/arctic_admin/pull/114

**Comment by cprodhomme** [comment]
i have done a new version with this fix : https://rubygems.org/gems/arctic_admin/versions/4.2.5
