### ISSUE TITLE
Error: File to import not found or unreadable: arctic_admin/base.

### ISSUE THREAD

**Issue by rashmi0601** [cprodhomme/arctic_admin#119]
Following https://github.com/cprodhomme/arctic_admin I have added
 in the gem file

` gem 'arctic_admin'`
in /app/assets/javascripts/active_admin.js file

`//= require arctic_admin/base`

in /app/assets/stylesheets/active_admin.scss file

`@import "arctic_admin/base";`

in active_admin.rb

```
 meta_tags_options = { viewport: 'width=device-width, initial-scale=1' }
    config.meta_tags = meta_tags_options
    config.meta_tags_for_logged_out_pages = meta_tags_options
```
in local theme is working. but in development environment I get

```
SassC::SyntaxError in ActiveAdmin::Devise::Sessions#new
Showing /usr/local/bundle/gems/activeadmin-2.12.0/app/views/layouts/active_admin_logged_out.html.erb where line #12 raised:

Error: File to import not found or unreadable: arctic_admin/base.
        on line 1:1 of app/assets/stylesheets/active_admin.scss
>> @import "arctic_admin/base";
```
Can someone please help me with this?

Thank you in advance.

**Comment by mpaluy** [comment]
How did you resolve this issue?
