### ISSUE TITLE
File to import not found or unreadable: '~arctic_admin/src/scss/main'

### ISSUE THREAD

**Issue by imsachinshah** [cprodhomme/arctic_admin#120]
This import is raising an error 

`@import '~arctic_admin/src/scss/main'; ` 

![image](https://github.com/cprodhomme/arctic_admin/assets/52409946/24d9cec4-b126-4079-a801-5dc353c170f5)

This is my file `active_admin.scss` 

![image](https://github.com/cprodhomme/arctic_admin/assets/52409946/2cf4d7d0-e75a-4898-8236-b53da3059f97)

I think this file's location has changed and is not UPDATED in the README file

**Comment by cprodhomme** [comment]
Hello,

Could you please add more informations please :

- The location of your .Scss file
- Your gemfile
- thé version you use

Thanks

**Comment by imsachinshah** [comment]
the file is located at `app/assets/stylesheets/active_admin.scss`

gemfile:

![image](https://github.com/cprodhomme/arctic_admin/assets/52409946/f88c9286-37d9-4ad8-a406-c52a2294bb68)

version is 4.2.6

I have solved the issue without importing that file 

Thank you for your response @cprodhomme
