### ISSUE TITLE
"New" form Styling broken

### ISSUE THREAD

**Issue by Divepit** [cprodhomme/arctic_admin#45]
Hello!

I created a model called "Button" which seems to have broken the Styling of the create action within arctic admin:

![image](https://user-images.githubusercontent.com/17721462/45888108-915c1600-bdbd-11e8-9263-fbffc61a43b6.png)

Is there a fix to this that does not include renaming the resource?

**Comment by cle61** [comment]
Maybe you should try to change the class 'button' of the form ?

**Comment by Divepit** [comment]
I'm sorry I think I'm not sure where/how I can do that :/
