### ISSUE TITLE
Batch action button

### ISSUE THREAD

**Issue by MarcAndreG** [cprodhomme/arctic_admin#46]
It seem like i have a problem with batch action button..

Its a fresh rails install with the theme on.

The button is disabled and clicked..

<img width="1188" alt="screen shot 2018-09-23 at 2 21 22 pm" src="https://user-images.githubusercontent.com/13788169/45931428-1a995700-bf3c-11e8-8540-f8855a9cc4af.png">

<img width="547" alt="screen shot 2018-09-23 at 2 22 00 pm" src="https://user-images.githubusercontent.com/13788169/45931429-1d944780-bf3c-11e8-99fd-a7ec43656784.png">

**Comment by Voxoff** [comment]
@MarcAndreG did you find a workaround?

**Comment by MarcAndreG** [comment]
No.. i switch back to default active admin theme. Not because of this issue but for other reason.

**Comment by sikandartariq1** [comment]
Just need to select some row...
<img width="141" alt="Screenshot 2019-03-12 at 10 21 45 AM" src="https://user-images.githubusercontent.com/29854616/54176443-aa15d080-44b0-11e9-8cc1-e330190292c4.png">
