### ISSUE TITLE
Up/Down Triangle broken

### ISSUE THREAD

**Issue by purple-sinhyeok** [cprodhomme/arctic_admin#50]
Hello!

activeadmin (1.4.3)
activeadmin_addons (1.7.0)

arctic_admin
v1.5.2
![스크린샷 2019-03-11 오전 11 51 10](https://user-images.githubusercontent.com/44961659/54097667-82f9c900-43f4-11e9-88e2-e8ce86fdda45.png)

v2.0.0
![스크린샷 2019-03-11 오전 11 52 07](https://user-images.githubusercontent.com/44961659/54097671-85f4b980-43f4-11e9-97c0-63f5ff6a9e85.png)

Thank you for nice theme :)

**Comment by cprodhomme** [comment]
hmm i will check that !

**Comment by godavid** [comment]
I worked around this problem by adding the old dependency gem to the gemfile:

`gem "font-awesome-rails"`

And importing fontawesome at the end of active_admin.scss

`@import "font-awesome";`

**Comment by cprodhomme** [comment]
What is your gemfile ?
I can't reproduce the error

**Comment by davisinfo** [comment]
It happens to me also using rails 5.2.2 and activeadmin 1.4.3

**Comment by davisinfo** [comment]
[Gemfile.zip](https://github.com/cprodhomme/arctic_admin/files/2993014/Gemfile.zip)

**Comment by purple-sinhyeok** [comment]
Resolved in 2.0.1. Thank you!
