### ISSUE TITLE
ActiveAdmin 2.0.0 support

### ISSUE THREAD

**Issue by neidiom** [cprodhomme/arctic_admin#51]
Hi, do you plan to support ActiveAdmin 2.0.0 ? Thank you for your work.

**Comment by cprodhomme** [comment]
I want to support ActiveAdmin 2.0.0 but i don't know when ^^

**Comment by wasifhossain** [comment]
we will eagerly wait for this awesome gem to support **ActiveAdmin 2.0.0+** and only then, we would be able to update **Rails to 6**, which is ready to be released soon enough.

**Comment by cprodhomme** [comment]
Done https://github.com/cprodhomme/arctic_admin/releases/tag/V3.0.0
