### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by mberbero** [cprodhomme/arctic_admin#54]
When I activate your theme, I get a jQuery is not defined error.

**Comment by cprodhomme** [comment]
What version of the theme are you using ?

**Comment by mberbero** [comment]
How can I learn version

**Comment by cprodhomme** [comment]
In your gemfile.lock

**Comment by mberbero** [comment]
![artc](https://user-images.githubusercontent.com/40326463/57607549-fabeae00-7573-11e9-8fe7-efc04efbcc41.jpg)

**Comment by mberbero** [comment]
I found the problem. I am using (// = stub active_admin) in application.js. So jquery cannot be defined. But this is your theme. vanilla active is not involved in.
