### ISSUE TITLE
Icons not showing @ 2.1.0

### ISSUE THREAD

**Issue by pctechjon** [cprodhomme/arctic_admin#57]
I know there's [issue 39](https://github.com/cprodhomme/arctic_admin/issues/39) with probably the same issue, but I'm experiencing it in a version after 2.0.1 where it was fixed.

```
rails (4.2.11.1)
arctic_admin (2.1.0)
activeadmin (1.4.3)
```

app/assets/javascripts/active_admin.js
(active_admin/base removed already)
```
//= require arctic_admin/base
```

app/assets/stylesheets/active_admin.scss
(active_admin/base removed already)
```
@import "arctic_admin/base";
@import "active_admin/mixins";
```

config/initializers/active_admin.rb
```
Added:
  meta_tags_options = { viewport: 'width=device-width, initial-scale=1' }
  config.meta_tags = meta_tags_options
  config.meta_tags_for_logged_out_pages = meta_tags_options
```

Example screenshot of index column headers. Other icons like the arrows for the side-bar menu are also missing.

![arctic_admin_no_icons](https://user-images.githubusercontent.com/168713/59959566-d2ce3e80-947f-11e9-915a-30609a0a28ec.PNG)

I would be open to using a CDN for the FA icons if necessary, just not sure how to configure that in ActiveAdmin.

**Comment by SimFortier11** [comment]
adding @import 'font_awesome5_webfont';  in _base.scss solves the problem
( don't forget to add font_awesome5_rails in the gemfile )

**Comment by cprodhomme** [comment]
duplicate to https://github.com/cprodhomme/arctic_admin/issues/39
