### ISSUE TITLE
How to adjust the font and font size on the activeadmin by the arctic_admin

### ISSUE THREAD

**Issue by bluesky0318** [cprodhomme/arctic_admin#58]
I used the arctic_admin to decorate the activeadmin on my app. it is nice for me, there is a question, How to adjust the font and font size on the activeadmin by the arctic_admin?? the character show so smaller for me. thanks

**Comment by cprodhomme** [comment]
I have'nt yet set up scss variable for that, sorry :s

**Comment by bluesky0318** [comment]
still thanks for your reply.
