### ISSUE TITLE
filter js window behavior

### ISSUE THREAD

**Issue by vieditcom** [cprodhomme/arctic_admin#62]
[Screenshot](https://i.imgur.com/lTvLfrK.png)
One click - filter window is showing
Second click - window is moving left instead of hiding.
Next clicks - still moving to the left.
However in mobile version view in Chrome everything is ok and window hiding normally after click.
Please check and respond.

**Comment by vieditcom** [comment]
Looks like it depends on browser. This bug exist in Opera(I'm using Linux official version) for sure.

**Comment by vieditcom** [comment]
Really annoying...

**Comment by cprodhomme** [comment]
Sorry, i'm really busy. Can you make a pull request for fix that ? :)

**Comment by cprodhomme** [comment]
Fix in the

**Comment by cprodhomme** [comment]
Use the new version of `arctic_admin 3.1.1`
