### ISSUE TITLE
Icons not loading in articadmin - active admin 2.2.0

### ISSUE THREAD

**Issue by Saravanan-Siva** [cprodhomme/arctic_admin#63]
vendor/assests/stylesheet.scss----

// Active Admin's got SASS!

@import "font-awesome";
@import "arctic_admin/base";
@import 'activeadmin/quill_editor_input';
@import 'font-awesome.css';

gem file----
gem 'arctic_admin'
gem 'activeadmin_quill_editor'
gem 'font-awesome-sass'
gem "font-awesome-rails"
gem 'bootstrap-sass'
gem 'sassc-rails', '~> 2.1', '>= 2.1.1'

(rails 5,activeadmin-2.2.0,    arctic_admin (3.0.0)

**Comment by EvanBrightside** [comment]
@Saravanan-Siva 
adding @import 'font_awesome5_webfont'; in _base.scss solves the problem
( don't forget to add font_awesome5_rails in the gemfile )
