### ISSUE TITLE
select2 not working in version 3.2.0

### ISSUE THREAD

**Issue by adept-akanksha** [cprodhomme/arctic_admin#77]
**Describe the bug**
Select2 is not working in the expected manner

**Screenshots**
![Screenshot 2020-06-03 at 9 36 48 PM](https://user-images.githubusercontent.com/64303936/83660371-6130c700-a5e2-11ea-9bed-0aa7f50ef26f.png)

**Gemfile**
arctic_admin (3.2.0)
rails (6.0.3.1)

**Comment by cprodhomme** [comment]
select2 is not installed with arctic_admin
