### ISSUE TITLE
Is there something like activeadmin-sortable?

### ISSUE THREAD

**Issue by ckhung5** [cprodhomme/arctic_admin#86]
Hi,
**Is your feature request related to a problem? Please describe.**
I am thinking whether arctic_admin has some kind of method to manually sort the position of my item in Item index page? I am trying to add this gem into it but it does not work
https://github.com/jcuervo/activeadmin-sortable

**Describe the solution you'd like**
To be able to sort a list with the position that I want

**Comment by cprodhomme** [comment]
Hello :) 

I don't think it comes from the gem because there is hardly any ruby in the library
If you want some help, please explain and put your complete error ;)

**Comment by ckhung5** [comment]
Hi @cprodhomme , 

Thank you for the reply. 

I do not think it is an error. It is more like a feature to implement "position". 

For example, I have a list of vendors that I wish to list them according to a position that I want as default is by alphabetically.

result:
Vendor A - 1
Vendor C - 2
Vendor B - 3

I saw that there are some solution in Rails that people implement "position" and you can drag and move these records.

Something like this 
https://www.youtube.com/watch?v=Aru-XvzzGjU

**Comment by cprodhomme** [comment]
I think you should write the functionnality in JS and not use the gem activeadmin-sortable (because the last commit was in 2013)
