### ISSUE TITLE
Adding additional fields to the login page

### ISSUE THREAD

**Issue by epidevops** [cprodhomme/arctic_admin#96]
Hi there, I am hoping you can provide some guidance  on how I can add additional fields to the login screen such as name.

<img width="421" alt="image" src="https://user-images.githubusercontent.com/41348221/168677424-ee2f2ad3-879b-4173-ae43-07a8f258f999.png">

**Comment by cprodhomme** [comment]
Sorry i have not idea how to do that.

It's a request for https://github.com/activeadmin/activeadmin
